version: '3.8'

services:
  web:
    image: suhan123/super_resolution:v1.0
    deploy:
      replicas: 3
    ports:
      - "5001-5003:5001"
    depends_on:
      - onnx
      - db
    networks:
      - app_network 

  onnx:
    image: suhan123/onnx_server:v1.0
    deploy:
      replicas: 3
    ports:
      - "8095-8097:6000"
    networks:
      - app_network  

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: image_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "23306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network 

  proxy-web:
    image: suhan123/nginx:v1.0
    container_name: rolling-server-web
    restart: always
    depends_on:
     - web
    ports:
     - '81:80'
    volumes:
     - ${PWD}/nginx/nginx.conf:/etc/nginx/conf.d
    networks:
     - app_network

  proxy-onnx:
   image: suhan123/nginx:v1.0
   container_name: rolling-onnx-lb
   restart: always
   ports:
    - '6000:80'
   volumes:
    - ${PWD}/nginx/nginx_onnx.conf:/etc/nginx/conf.d
   networks:
    - app_network
 
networks:
  app_network:
    driver: bridge  # web과 db가 연결되는 네트워크
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        ip_range: 172.20.0.0/24
        gateway: 172.20.0.1

volumes:
  db_data:
